### ISSUE TITLE
[FEAT] tmi 입력 및 방 입장 API

### ISSUE THREAD

**Issue by bbabbi** [NOW-SOPT-SOPKATHON-WEB1/SERVER#12]
## 📌 구현하려고 하는 것

방 입장 시 코드를 비교하고, 동일한 방 코드를 가지도록

## ✅ Tasks
- [x] 방 입장 코드 column 추가
- [x] 방 입장 코드에 따른 roomId 배정
- [x] 설정된 인원 초과 시, 입장 제한 기능
- [ ] 각 상황에 따른 errorMessage 반환
